import { type NextPage } from "next";
import Head from "next/head";

import Header from "@/components/Header/Header";
import { api } from "@/utils/api";


const Dashboard: NextPage = () => {
    const hello = api.example.hello.useQuery({ text: "from tRPC" });
    console.log(hello.trpc.path);

    return (
        <>
            <Head>
                <title>Create T3 App</title>
                <meta name="description" content="Generated by create-t3-app" />
            </Head>
            <div className="flex justify-center items-center">
                <Header
                    title="DASHBOARD"
                    subtitle="Welcome to your dashboard!"
                />
            </div>

        </>

    );
};

export default Dashboard;
