import { type NextPage } from "next";
import Head from "next/head";

import { api } from "@/utils/api";


const Home: NextPage = () => {
  const hello = api.example.hello.useQuery({ text: "from tRPC" });
  console.log(hello.trpc.path);

  return (
    <Head>
      <title>Create T3 App</title>
      <meta name="description" content="Generated by create-t3-app" />
      <meta
        name="viewport"
        content="width=device-width, initial-scale=1"
      />
      <link rel="icon" href="/favicon.ico" />
    </Head>
  );
};

export default Home;
