import { SignInButton, UserButton, useUser } from "@clerk/nextjs";
import { type NextPage } from "next";
import Head from "next/head";

import { api } from "@/utils/api";

const Home: NextPage = () => {
  const hello = api.example.hello.useQuery({ text: "from tRPC" });
  console.log(hello.trpc.path);

  const { isSignedIn, user } = useUser();

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">

        <h1 className="text-6xl font-bold text-white">Welcome to t3-Dashboard!</h1>
        <div className="text-black bg-teal-300 rounded-sm">
          {!isSignedIn && (<SignInButton />)}
          {!!isSignedIn && (<><div className="text-black ">Hello, {user.firstName}</div> <UserButton /></>)}
        </div>

      </main>
    </>
  );
};

export default Home;
